export interface RssItem {
  guid: string;
  title: string;
  link: string;
  pubDate: Date;
  description: string;
  content: string;
}

export interface OgTags {
  title: string;
  description: string;
  imageUrl?: string;
}

// Env is the global interface generated by `wrangler types` in worker-configuration.d.ts,
// extended with secrets in src/worker-env.d.ts. Do not redeclare it here.
